mtime = 1687855889
[[pkgs]]
type = "github"
distrib = "python-lib-template"
package = "python_lib_template-0.1.0-py3-none-any"
ext = "whl"
sha256 = "1cff00579d02108a3eee58d8a59fb113fdd4bb6906945bc9ec1b40f67c1cda00"
url = "https://api.github.com/repos/astaralabs/astaralabs-pypi-pkg-repo/releases/assets/114522460"

[pkgs.meta]
name = "python-lib-template"
version = "0.1.0"
filetype = "bdist_wheel"
pyversion = "py3"
metadata_version = "2.1"
summary = ""
home_page = ""
author = "alejandrodob"
author_email = "alejandro.dominguez.b@astara.com"
maintainer = ""
maintainer_email = ""
license = ""
description = "# python-lib-template\n\nA template for Python libraries\n\n## Included tools\n\n- [Poetry](https://python-poetry.org/) for handling the project dependencies, building and (in the future) publishing the package.\n- [MyPy](https://www.mypy-lang.org/) for type checking.\n- [Ruff](https://beta.ruff.rs/docs/) for linting (configured to auto fix whenever possible).\n- [Black](https://black.readthedocs.io/en/stable/index.html) for autoformatting.\n- [Pytest](https://pytest.org/) for testing.\n\n## Usage\n\nAfter using the template for a new library repository, rename the package folder `python_lib_template` to your library name and do a global search of the string \"python_lib_template\" and replace it for your library name too.\n\n## Dependencies\n\nYou will need to have Poetry [installed](https://python-poetry.org/docs/#installation).\n\nThen, to install all the dependencies, run `poetry install`.\n\n## Testing, linting, formatting...\n\nRun the tests with `poetry run pytest`.\n\nFor running the linter with autofixing: `poetry run ruff .`. (Ruff configuration is located in [pyproject.toml](pyproject.toml)).\n\nBlack can be used to format the files with `poetry run black .` (Black configuration is located in [pyproject.toml](pyproject.toml)).\n\n## Releases\n\nAs of today, GitHub Package Repository does not support Python packages. For that reason, we will install the package directly from GitHub, as explained [here](https://pip.pypa.io/en/stable/topics/vcs-support/).\n"
keywords = ""
classifiers = "Programming Language :: Python :: 3"
download_url = ""
comment = ""
md5_digest = "a98271448ff8935e1f18423c4ac945d8"
sha256_digest = "1cff00579d02108a3eee58d8a59fb113fdd4bb6906945bc9ec1b40f67c1cda00"
blake2_256_digest = "d1206ec15f63e8e37a7e3d142c5da31cd8844c8e74dcf4975e9809cf6b6e5f03"
requires_python = ">=3.10,<4.0"
description_content_type = "text/markdown"
":action" = "file_upload"
protocol_version = "1"
distrib = "python-lib-template"
sha256 = "1cff00579d02108a3eee58d8a59fb113fdd4bb6906945bc9ec1b40f67c1cda00"
